// Copyright 2026 Ekumen, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#ifndef ROSIDL_RUNTIME_CPP__EXPERIMENTAL__TRAITS_HPP_
#define ROSIDL_RUNTIME_CPP__EXPERIMENTAL__TRAITS_HPP_

#include <cstdint>
#include <iostream>
#include <type_traits>
#include <string>

#include "rosidl_runtime_cpp/traits.hpp"
#include "rosidl_runtime_cpp/experimental/string.hpp"

namespace rosidl_runtime_cpp
{

// Get the ExternalStorage type from T, or void if it doesn't exist
template<typename T, typename = void>
struct external_storage_type
{
  using type = void;
};

template<typename T>
struct external_storage_type<T, std::void_t<typename T::ExternalStorage>>
{
  using type = typename T::ExternalStorage;
};

template<typename T>
using external_storage_type_t = typename external_storage_type<T>::type;

}  // namespace rosidl_runtime_cpp

// value_to_yaml overloads for experimental string types, generated by rosidl_generator_cpp.
// Covers rosidl_runtime_cpp::{,Bounded}{,W}String as instances of BasicString<CharT, N>.
namespace rosidl_generator_traits
{

template<typename CharT, std::size_t UpperBound>
inline void value_to_yaml(
  const rosidl_runtime_cpp::BasicString<CharT, UpperBound> & s,
  std::ostream & out)
{
  value_to_yaml(std::basic_string<CharT>(s.begin(), s.end()), out);
}

}  // namespace rosidl_generator_traits

#endif  // ROSIDL_RUNTIME_CPP__EXPERIMENTAL__TRAITS_HPP_
