# Copyright 2026 Ekumen, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Tests for generated experimental Python message classes.

These tests verify that the experimental messages generated by
rosidl_generator_py produce working classes backed by the experimental
container types from rosidl_runtime_py.experimental.
"""

import pytest

from rosidl_runtime_py.experimental import (
    Array,
    BoundedSequence,
    BoundedString,
    BoundedWString,
    Dtype,
    MessageInitialization,
    Scalar,
    Sequence,
    SequenceConstraint,
    String,
    StringConstraint,
    WString,
)


# Import generated experimental messages.
# These are generated from the same IDL files as the standard messages
# but under the experimental subpackage.
from rosidl_generator_py.msg.experimental import BasicTypes
from rosidl_generator_py.msg.experimental import Constants
from rosidl_generator_py.msg.experimental import Defaults
from rosidl_generator_py.msg.experimental import Strings
from rosidl_generator_py.msg.experimental import WStrings
from rosidl_generator_py.msg.experimental import Arrays
from rosidl_generator_py.msg.experimental import UnboundedSequences
from rosidl_generator_py.msg.experimental import BoundedSequences
from rosidl_generator_py.msg.experimental import Nested


# ---------------------------------------------------------------------------
# BasicTypes
# ---------------------------------------------------------------------------

class TestBasicTypes:

    def test_default_construction(self):
        msg = BasicTypes()
        # All scalar fields should be Scalar instances
        assert isinstance(msg.bool_value, Scalar)
        assert isinstance(msg.byte_value, Scalar)
        assert isinstance(msg.char_value, Scalar)
        assert isinstance(msg.float32_value, Scalar)
        assert isinstance(msg.float64_value, Scalar)
        assert isinstance(msg.int8_value, Scalar)
        assert isinstance(msg.uint8_value, Scalar)
        assert isinstance(msg.int16_value, Scalar)
        assert isinstance(msg.uint16_value, Scalar)
        assert isinstance(msg.int32_value, Scalar)
        assert isinstance(msg.uint32_value, Scalar)
        assert isinstance(msg.int64_value, Scalar)
        assert isinstance(msg.uint64_value, Scalar)

    def test_default_values_are_zero(self):
        msg = BasicTypes()
        assert msg.bool_value.value == False  # noqa: E712
        assert msg.float32_value.value == 0.0
        assert msg.int32_value.value == 0
        assert msg.uint64_value.value == 0

    def test_scalar_assignment(self):
        msg = BasicTypes()
        msg.int32_value.value = 42
        assert msg.int32_value.value == 42

    def test_equality(self):
        a = BasicTypes()
        b = BasicTypes()
        assert a == b
        a.int32_value.value = 99
        assert a != b

    def test_skip_initialization(self):
        msg = BasicTypes(_init=MessageInitialization.SKIP)
        # Should still be Scalar instances
        assert isinstance(msg.int32_value, Scalar)

    def test_constraints_class_exists(self):
        c = BasicTypes.Constraints()
        assert c == BasicTypes.Constraints()

    def test_repr(self):
        msg = BasicTypes()
        r = repr(msg)
        assert 'BasicTypes' in r


# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

class TestConstants:

    def test_constants_accessible(self):
        assert hasattr(Constants, 'BOOL_CONST')
        assert Constants.BOOL_CONST is True
        assert hasattr(Constants, 'INT32_CONST')
        assert Constants.INT32_CONST == -30000
        assert hasattr(Constants, 'FLOAT64_CONST')
        assert abs(Constants.FLOAT64_CONST - 1.125) < 1e-6


# ---------------------------------------------------------------------------
# Strings
# ---------------------------------------------------------------------------

class TestStrings:

    def test_string_fields(self):
        msg = Strings()
        assert isinstance(msg.string_value, String)
        assert isinstance(msg.bounded_string_value, BoundedString)

    def test_string_assign(self):
        msg = Strings()
        msg.string_value.assign('hello')
        assert str(msg.string_value) == 'hello'

    def test_equality(self):
        a = Strings()
        b = Strings()
        assert a == b
        a.string_value.assign('different')
        assert a != b


# ---------------------------------------------------------------------------
# WStrings
# ---------------------------------------------------------------------------

class TestWStrings:

    def test_wstring_fields(self):
        msg = WStrings()
        assert isinstance(msg.wstring_value, WString)
        assert isinstance(msg.array_of_wstrings, Array)
        assert isinstance(msg.bounded_sequence_of_wstrings, BoundedSequence)
        assert isinstance(msg.unbounded_sequence_of_wstrings, Sequence)


# ---------------------------------------------------------------------------
# Arrays
# ---------------------------------------------------------------------------

class TestArrays:

    def test_array_fields(self):
        msg = Arrays()
        # Primitive arrays should be Array instances
        assert isinstance(msg.bool_values, Array)
        assert isinstance(msg.int32_values, Array)
        assert isinstance(msg.float32_values, Array)
        assert isinstance(msg.string_values, Array)

    def test_primitive_array_length(self):
        msg = Arrays()
        assert len(msg.bool_values) == 3
        assert len(msg.int32_values) == 3
        assert len(msg.float32_values) == 3

    def test_array_element_access(self):
        msg = Arrays()
        msg.int32_values[0] = 42
        assert msg.int32_values[0] == 42

    def test_equality(self):
        a = Arrays()
        b = Arrays()
        assert a == b


# ---------------------------------------------------------------------------
# UnboundedSequences
# ---------------------------------------------------------------------------

class TestUnboundedSequences:

    def test_sequence_fields(self):
        msg = UnboundedSequences()
        assert isinstance(msg.bool_values, Sequence)
        assert isinstance(msg.int32_values, Sequence)
        assert isinstance(msg.string_values, Sequence)

    def test_sequence_starts_empty(self):
        msg = UnboundedSequences()
        assert len(msg.bool_values) == 0
        assert len(msg.int32_values) == 0

    def test_sequence_append(self):
        msg = UnboundedSequences()
        msg.int32_values.append(42)
        msg.int32_values.append(99)
        assert len(msg.int32_values) == 2
        assert msg.int32_values[0] == 42

    def test_constraints_class(self):
        c = UnboundedSequences.Constraints()
        # Unbounded sequences should have SequenceConstraint fields
        assert hasattr(c, 'bool_values')
        assert isinstance(c.bool_values, SequenceConstraint)


# ---------------------------------------------------------------------------
# BoundedSequences
# ---------------------------------------------------------------------------

class TestBoundedSequences:

    def test_bounded_sequence_fields(self):
        msg = BoundedSequences()
        assert isinstance(msg.bool_values, BoundedSequence)
        assert isinstance(msg.int32_values, BoundedSequence)

    def test_bounded_sequence_limit(self):
        msg = BoundedSequences()
        assert msg.bool_values.max_size == 3
        assert msg.int32_values.max_size == 3


# ---------------------------------------------------------------------------
# Nested
# ---------------------------------------------------------------------------

class TestNested:

    def test_nested_field(self):
        msg = Nested()
        assert isinstance(msg.basic_types_value, BasicTypes)

    def test_nested_equality(self):
        a = Nested()
        b = Nested()
        assert a == b
        a.basic_types_value.int32_value.value = 42
        assert a != b

    def test_constraints(self):
        c = Nested.Constraints()
        assert hasattr(c, 'basic_types_value')


# ---------------------------------------------------------------------------
# Defaults
# ---------------------------------------------------------------------------

class TestDefaults:

    def test_default_values_applied(self):
        msg = Defaults()
        # The Defaults message has fields with default annotations
        assert msg.bool_value.value is True
        assert msg.int8_value.value == -50
        assert msg.uint8_value.value == 200
        assert abs(msg.float32_value.value - 1.125) < 1e-5
        assert abs(msg.float64_value.value - 1.125) < 1e-9

    def test_defaults_only(self):
        msg = Defaults(_init=MessageInitialization.DEFAULTS_ONLY)
        assert isinstance(msg.bool_value, Scalar)
        assert msg.bool_value.value is True

    def test_zero_does_not_apply_defaults(self):
        msg = Defaults(_init=MessageInitialization.ZERO)
        # With ZERO, defaults should not be applied
        assert isinstance(msg.bool_value, Scalar)

    def test_skip(self):
        msg = Defaults(_init=MessageInitialization.SKIP)
        assert isinstance(msg.bool_value, Scalar)
