@# generated from rosidl_typesupport_xcdr_cpython/resource/srv__type_support.cpp.em
@# with input from @(package_name):@(interface_path)
@# generated code does not contain a copyright notice
@{
# Get optional force_experimental flag (set by experimental wrapper templates).
try:
    force_experimental
except NameError:
    force_experimental = False
}@
@#######################################################################
@# Request, Response and Event messages are generated by the msg template.
@#######################################################################
@{
for message in [
        service.request_message,
        service.response_message,
        service.event_message,
]:
    TEMPLATE(
        'msg__type_support.cpp.em',
        package_name=package_name, interface_path=interface_path,
        message=message, force_experimental=force_experimental)
}@
@# Service handle generation is Phase 5; only the constituent messages are
@# emitted for now so that packages containing services still build.
