@# generated from rosidl_typesupport_xcdr_cpython/resource/srv__type_support.cpp.em
@# with input from @(package_name):@(interface_path)
@# generated code does not contain a copyright notice
@{
# Get optional force_experimental flag (set by experimental wrapper templates).
try:
    force_experimental
except NameError:
    force_experimental = False
}@
@#######################################################################
@# Request, Response and Event messages are generated by the msg template.
@#######################################################################
@{
# Request and Response are same-package messages and get a full cpython
# typesupport.  The Event message is NOT emitted: its payload references
# service_msgs::msg::ServiceEventInfo, a cross-package dependency that does not
# generate a cpython typesupport (dependency packages use the c/cpp/introspection
# generators, not rosidl_typesupport_xcdr_cpython).  A static
# get_message_type_support_handle<service_msgs::msg::ServiceEventInfo>() would
# not link.  Event support lands with Phase 5 services.
for message in [
        service.request_message,
        service.response_message,
]:
    TEMPLATE(
        'msg__type_support.cpp.em',
        package_name=package_name, interface_path=interface_path,
        message=message, force_experimental=force_experimental)
}@
@# Service handle generation is Phase 5; only the constituent messages are
@# emitted for now so that packages containing services still build.
