services:
  base_ros_environ:
    user: ${USERID:-1000}:${GROUPID:-1000}
    hostname: zcr-baseline-ros
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - XAUTHORITY=${XAUTHORITY:-/tmp/.docker.xauth}
      - ROS_DOMAIN_ID=${ROS_DOMAIN_ID:-90}
    build:
      context: ..
      dockerfile: docker/Dockerfile
      target: base_ros
      args:
        UID: $USERID
        GID: $GROUPID
    image: ekumenlabs/zcr-baseline-ros
    container_name: zcr-baseline-ros
    volumes:
      - ../data:/home/developer/data:rw
      - ../tools:/home/developer/tools:ro
      - /tmp:/tmp:rw

  patched_ros_environ:
    user: ${USERID:-1000}:${GROUPID:-1000}
    hostname: zcr-ros
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - XAUTHORITY=${XAUTHORITY:-/tmp/.docker.xauth}
      - ROS_DOMAIN_ID=${ROS_DOMAIN_ID:-90}
    build:
      context: ..
      dockerfile: docker/Dockerfile
      target: patched_ros
      args:
        UID: $USERID
        GID: $GROUPID
    image: ekumenlabs/zcr-ros
    container_name: zcr-ros
    volumes:
      - ../data:/home/developer/data:rw
      - ../tools:/home/developer/tools:ro
      - /tmp:/tmp:rw

  dev_environ:
    user: ${USERID:-1000}:${GROUPID:-1000}
    hostname: zcr-dev
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - XAUTHORITY=${XAUTHORITY:-/tmp/.docker.xauth}
      - ROS_DOMAIN_ID=${ROS_DOMAIN_ID:-90}
    build:
      context: ..
      dockerfile: docker/Dockerfile
      target: dev_environ
      args:
        UID: $USERID
        GID: $GROUPID
    image: ekumenlabs/zcr-dev
    container_name: zcr-dev
    stdin_open: true
    tty: true
    volumes:
      - zero_copy_rosidl_persistence:/home/developer/ws/.persistence
      - ../code:/home/developer/ws/src
      - ../data:/home/developer/data
      - ../tools:/home/developer/tools
      - /tmp:/tmp

volumes:
  zero_copy_rosidl_persistence:
